// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCsYATLwPkr50Ld5nAtvLlf_jFnmVhxM',
    appId: '1:1054462390932:web:d5efd27672472c0f703a81',
    messagingSenderId: '1054462390932',
    projectId: 'web2app-51b36',
    authDomain: 'web2app-51b36.firebaseapp.com',
    databaseURL: 'https://web2app-51b36-default-rtdb.firebaseio.com',
    storageBucket: 'web2app-51b36.appspot.com',
    measurementId: 'G-GB8Q95YHJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD06p06mWk8Qgr21s8Lwe5c3oan4nMWgg',
    appId: '1:1054462390932:android:9d0e7c9469f1ed7d703a81',
    messagingSenderId: '1054462390932',
    projectId: 'web2app-51b36',
    databaseURL: 'https://web2app-51b36-default-rtdb.firebaseio.com',
    storageBucket: 'web2app-51b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJpIKpRuRu29uF5a_h85Q6I0EAKn8miE',
    appId: '1:1054462390932:ios:309ea179e8c7a803703a81',
    messagingSenderId: '1054462390932',
    projectId: 'web2app-51b36',
    databaseURL: 'https://web2app-51b36-default-rtdb.firebaseio.com',
    storageBucket: 'web2app-51b36.appspot.com',
    iosBundleId: 'com.phimask.network',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpJpIKpRuRu29uF5a_h85Q6I0EAKn8miE',
    appId: '1:1054462390932:ios:309ea179e8c7a803703a81',
    messagingSenderId: '1054462390932',
    projectId: 'web2app-51b36',
    databaseURL: 'https://web2app-51b36-default-rtdb.firebaseio.com',
    storageBucket: 'web2app-51b36.appspot.com',
    iosBundleId: 'com.phimask.network',
  );
}
